### ISSUE TITLE
Irrigation Unlimited Card: Filter over main controller entity

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation-unlimited-card#11]
**Is your feature request related to a problem? Please describe.**
The Irrigation Unlimited Card works well for multiple controllers. A friend of mine is running Home Assistant on one central machine but servicing 19 different remote sites that are all linked on UI with individual controllers, and each user responsible for these 19 remote sites has a dedicated Home Assistant dashboard. It would be nice to use the UI companion card but be able to filter over each controller on the card.

**Describe the solution you'd like**
```
type: custom:irrigation-unlimited-card
always_show_zones: false
always_show_sequences: false
show_controller: #this will only show those controllers that are within the target entity list
  target:
      entity_id: 
        - binary_sensor.irrigation_unlimited_c1_m
        - binary_sensor.irrigation_unlimited_c2_m
        - binary_sensor.irrigation_unlimited_c6_m
```

**Describe alternatives you've considered**
The only other way is to use other custom cards which is obviously an option. However, since UI is so flexible and the companion card really matching the functionality of the UI integration, it would be preferred to use the actual companion card and make it more flexible. 

**Additional context**
Thanks Robert for looking into this - I would assume that this filter option is relatively simple to add since you already have card options integrated and custom display of zones and sequences.

**Comment by rgc99** [comment]
This functionality does exist however the card properties editor appears to be a bit broken. This request is similar to issue [2](https://github.com/rgc99/irrigation-unlimited-card/issues/2). Edit the card configuration and add a `show_controllers:` line with a CSV list of the controllers you want to display. You may or may not need the trailing comma.
```yaml
type: custom:irrigation-unlimited-card
name: Irrigation Unlimited
always_show_zones: false
always_show_sequences: false
show_controllers: 1,
```
The card is due for some work.
